services:
  workspace:
    container_name: zenn-docs-workspace
    build: ./dockers/workspace
    tty: true
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules:
